#!/usr/bin/with-contenv bash
# TODO: actually start the keeper here
set -eux

echo "RPC_HOST: ${RPC_HOST}"
echo "RPC_PORT: ${RPC_PORT:-}"

# TODO: wait for consul

# TODO: read ETH_FROM address out of consul?
echo "ETH_FROM: ${ETH_FROM}"

# make sure transactions aren't stuck
# TODO: next version of plunger removes the source flag since parity_txqueue is the only option
makerdao-helper plunger --source parity_txqueue --wait "$ETH_FROM"

# TODO: don't run as root
case "$KEEPER" in
        arbitrage)
            exec makerdao-helper arbitrage-keeper \
              --eth-from "$ETH_FROM" \
              --tub-address "$TUB_ADDRESS" \
              --tap-address "$TAP_ADDRESS" \
              --oasis-address "$OASIS_ADDRESS" \
              --oasis-support-address "${OASIS_SUPPORT_ADDRESS:-}" \
              --tx-manager "${TX_MANAGER:-}" \
              --base-token "$BASE_TOKEN" \
              --min-profit "${MIN_PROFIT}" \
              --max-engagement "${MAX_ENGAGEMENT}" \
            ;
            ;;

        auction|bite|cdp|market-maker)
            echo "Keeper help not yet written"
            exit 1
            ;;

        *)
            echo "Unknown keeper"
            exit 1
esac
